name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
