name: CI

on: [push]

jobs:
  build:
    name: Build, lint, and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test --ci --coverage --maxWorkers=2
